---
name: Contributors
on:
  schedule:
    - cron: 0 2 * * 0  # At 01:00 on Sunday.
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: manual run
        required: false
        default: ''
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: true
